### ISSUE TITLE
Loaded image is flipped 180 on the x-axis 

### ISSUE THREAD

**Issue by MunWeiKhong** [gindemit/unity-rlottie#10]
![image](https://github.com/gindemit/unity-rlottie/assets/134491176/776940b1-d71d-4a4f-a18e-3a6b668d13b0)

After placing the a file that has been converted from .json to .txt file into the AnimationJson of AnimatedImage script, the the image is loaded and runs the animation, but it is flipped 180 on the x-axis

**Comment by gindemit** [comment]
Hey @MunWeiKhong, thanks for the report!
Right now to fix this issue, please make the Y scale of your RawImage game object transform "-1".
Like on this screenshot:
![image](https://github.com/gindemit/unity-rlottie/assets/5675979/d5810a82-d176-4b9e-9dcc-034ff818bf49)

**Comment by MunWeiKhong** [comment]
Thanks for dropping info for a temporary fix. 
Will leave this issue as open until a proper fix has been implemented.
