### ISSUE TITLE
DllNotFoundException: LottiePlugin assembly on MacOS

### ISSUE THREAD

**Issue by chile109** [gindemit/unity-rlottie#11]
Hello, I followed the manual to open sample scene but get the DLL error.
<img width="1119" alt="截圖 2023-06-15 下午5 22 03" src="https://github.com/gindemit/unity-rlottie/assets/13402112/769532b9-b461-4070-9bea-2b8f336bbff9">

This is my environment detail:
- Apple M2 chip Ventura
- Unity 2021.3.16f1

I saw there is also a similar issue: https://github.com/gindemit/unity-rlottie/issues/6
How can I fixed that?

**Comment by chile109** [comment]
@simonpham After check your solution, seems like it need Cmake rebuild that rlottie?
Sorry I am a Unity Developer and have no experience how to do it, need more clues.

**Comment by gindemit** [comment]
Hello @chile109, thanks for trying out. It seems that the current compiled native libraries are targeting only x86_64 architecture. And you have the arm64 CPU.

You can check it yourself In terminal:

```
konstantingindemit@Konstantins-MBP OSX % file libLottiePlugin.dylib
libLottiePlugin.dylib: Mach-O 64-bit dynamically linked shared library x86_64
konstantingindemit@Konstantins-MBP OSX % file librlottie.dylib
librlottie.dylib: Mach-O 64-bit dynamically linked shared library x86_64
```

Can you please try out the attached files.
[Archive.zip](https://github.com/gindemit/unity-rlottie/files/11756753/Archive.zip)
You need to unpack the zip archive, close Unity project and replace the dylib files in the 
`git/unity-rlottie/unity/RLottieUnity/Assets/LottiePlugin/Plugins/OSX` folder.

With the attached files I get following in terminal:

```
konstantingindemit@Konstantins-MBP rlottieOSXArm64 % file libLottiePlugin.dylib 
libLottiePlugin.dylib: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit dynamically linked shared library x86_64
- Mach-O 64-bit dynamically linked shared library x86_64] [arm64:Mach-O 64-bit dynamically linked shared library arm64
- Mach-O 64-bit dynamically linked shared library arm64]
libLottiePlugin.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
libLottiePlugin.dylib (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
konstantingindemit@Konstantins-MBP rlottieOSXArm64 % file librlottie.dylib 
librlottie.dylib: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit dynamically linked shared library x86_64
- Mach-O 64-bit dynamically linked shared library x86_64] [arm64:Mach-O 64-bit dynamically linked shared library arm64
- Mach-O 64-bit dynamically linked shared library arm64]
librlottie.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
librlottie.dylib (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
```

**Comment by chile109** [comment]
Hey @gindemit , after replace the `libLottiePlugin.dylib` the plugin is working now.
Thanks for your help and Detailed explanation!
