### ISSUE TITLE
load pngs images inside lottie json

### ISSUE THREAD

**Issue by ammariqais** [gindemit/unity-rlottie#12]
i have lottie file that included pngs its works fine on lottiefiles.com but not working on unity no error, just empty not loaded the images
lottie file attchemnt 
[emote satan (1).txt](https://github.com/gindemit/unity-rlottie/files/11788197/emote.satan.1.txt)

**Comment by toboko** [comment]
I am trying to use in my project this package, and I have to report the same problem. In particular, I am using lottie in json format that contain png images in base64 format. The animation does not start, in fact nothing appears but no error is reported.

**Comment by gindemit** [comment]
Hello! Thanks for the interest in this plugin. 
Under the hood this plugin uses Samsungs rlottie library. As I see the .lottie format support was added 2 weeks ago to rlottie. 
https://github.com/Samsung/rlottie/pull/541

The native libraries that are included into the latest release do not contain those changes. I need to rebuild the native libraries for all platforms.
I plan to implement GitHub actions to simplify the process of building the native libraries. Writing the scripts for GitHub actions and making sure everything is working fine will take some time.

**Comment by gindemit** [comment]
Hey @ammariqais, I am affraid the rlottie library does not render text: https://github.com/Samsung/rlottie/issues/544

It means this plugin can render text only if the rlottie library supports that. In case it is not supported by rlottie library, please create an issue in their repository.

**Comment by DeWince** [comment]
also tried using lottie file with image both encoded in base 64 and accessed by url, both of them render and animate only vector part of lottie animation, images are rendered as grey pixels
Waiting for this issue to resolve, thanks for your work
