### ISSUE TITLE
Plugin does not support 'arm64' architecture in editor 

### ISSUE THREAD

**Issue by VTeselkin** [gindemit/unity-rlottie#18]
Plugin does not work on version Unity3d 2021 and older with processor support Apple Silicone (Macbook M1,M2)

`'/Applications/Unity/Hub/Editor/2021.3.29f1/Unity.app/Contents/Frameworks/Assets/LottiePlugin/Plugins/OSX/libLottiePlugin.dylib' (no such file), '/Applications/Unity/Hub/Editor/2021.3.29f1/Unity.app/Contents/Frameworks/Assets/LottiePlugin/Plugins/OSX/libLottiePlugin.dylib' (no such file), '/usr/lib/Assets/LottiePlugin/Plugins/OSX/libLottiePlugin.dylib' (no such file, not in dyld cache), 'Assets/LottiePlugin/Plugins/OSX/libLottiePlugin.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/Users/doc/guess-please/Assets/LottiePlugin/Plugins/OSX/libLottiePlugin.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/doc/guess-please/Assets/LottiePlugin/Plugins/OSX/libLottiePlugin.dylib' (no such file), '/Users/doc/guess-please/Assets/LottiePlugin/Plugins/OSX/libLottiePlugin.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))`

**Comment by gindemit** [comment]
Hello @VTeselkin, thanks for the interest in this plugin!
Can you please try out the plugin from the dev branch. I rebuild the native libraries in that branch. Or if it is problematic for you, you can wait until I release a new version of the plugin. I plan to make a release in the next week.

**Comment by VTeselkin** [comment]
I downloaded the plugin from the dev branch, the problem is the same: 
`Plugins: Couldn't open Assets/LottiePlugin/Plugins/OSX/libLottiePlugin.dylib, error: dlopen(Assets/LottiePlugin/Plugins/OSX/libLottiePlugin.dylib, 0x0002): tried: 'Assets/LottiePlugin/Plugins/OSX/libLottiePlugin.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OSAssets/LottiePlugin/Plugins/OSX/libLottiePlugin.dylib' (no such file), '/Applications/Unity/Hub/Editor/2021.3.29f1/Unity.app/Contents/Frameworks/Assets/LottiePlugin/Plugins/OSX/libLottiePlugin.dylib' (no such file), '/Applications/Unity/Hub/Editor/2021.3.29f1/Unity.app/Contents/Frameworks/Assets/LottiePlugin/Plugins/OSX/libLottiePlugin.dylib' (no such file), '/usr/lib/Assets/LottiePlugin/Plugins/OSX/libLottiePlugin.dylib' (no such file, not in dyld cache), 'Assets/LottiePlugin/Plugins/OSX/libLottiePlugin.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/Users/doc/guess-please/Assets/LottiePlugin/Plugins/OSX/libLottiePlugin.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/doc/guess-please/Assets/LottiePlugin/Plugins/OSX/libLottiePlugin.dylib' (no such file), '/Users/doc/guess-please/Assets/LottiePlugin/Plugins/OSX/libLottiePlugin.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))`

Unity3D 2021.3.29 Apple Silicone

**Comment by gindemit** [comment]
Hello @VTeselkin, can you please try with the latest changes in dev branch?
The arm64 was missing for OSX, sorry for that. Now it should work.

**Comment by VTeselkin** [comment]
Thanks, all worked!!!
