### ISSUE TITLE
Some animations from Lottiefiles aint recognized as lottie animation

### ISSUE THREAD

**Issue by JChudinov** [gindemit/unity-rlottie#21]
Good day. While using AnimatedImage component some animations are not recognized as lottie.

This is an example of animation that is not recognized:
https://lottiefiles.com/animations/merry-christmas-rHWirI2aZ2

This one works well:
https://lottiefiles.com/animations/radar-loading-quRoUzmGZN

Hope both links are valid. Tried to create own animation with lottiefiles, but mine one either fails.

**Comment by gindemit** [comment]
Hello @JChudinov, thanks for the report! 
It seems that the merry christmas animation uses some body movin features that are not supported by the rlottie library.
You can try the animation yourself with the rlottie online player:
http://rlottie.com/

This Unity plugin uses the rlottie library internally to render the animation to Unity Texture2D.

![image](https://github.com/gindemit/unity-rlottie/assets/5675979/9129a9b7-a538-432f-9e27-de44b3d2ea72)


You can review the supported features here:
https://github.com/Samsung/rlottie?tab=readme-ov-file#supported-after-effects-features
