### ISSUE TITLE
AnimatedImage script not showing its parameters after importing from git 

### ISSUE THREAD

**Issue by MunWeiKhong** [gindemit/unity-rlottie#9]
After importing the package into the project via git like in the Installation section of the guide, I am unable to use the AnimatedImage script, as it dose not show its fields after adding the component to an object even with RawImage on it

![image](https://github.com/gindemit/unity-rlottie/assets/134491176/acd546d6-131c-4a9a-8ced-c5d4c7d6d836)

I also get the following errors in the console.
![image](https://github.com/gindemit/unity-rlottie/assets/134491176/a1c1c051-e921-45b2-b0ac-84a23f5b764c)

I am not sure if I am missing any components or have not followed the guide properly. 
Hope to hear form you soon. 

P/S : If possible, do make a simple tutorial video to supplement the user guide you have posted. I am sure people will appreciate it.

**Comment by gindemit** [comment]
Hey @MunWeiKhong, thanks so much for finding it!

I just published a bugfix release 0.2.1 version.
Please try it out: https://github.com/gindemit/unity-rlottie/releases/tag/0.2.1

Please let me know if it works now for you.
